/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Allegion_Hadoop_TransVideoSplitTool */

#ifndef _Included_Allegion_Hadoop_TransVideoSplitTool
#define _Included_Allegion_Hadoop_TransVideoSplitTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Allegion_Hadoop_TransVideoSplitTool
 * Method:    InitFFmpeg
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_TransVideoSplitTool_InitFFmpeg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Allegion_Hadoop_TransVideoSplitTool
 * Method:    SetTransVideoSplitReadCallBack
 * Signature: (JLjava/lang/Object;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_TransVideoSplitTool_SetTransVideoSplitReadCallBack
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     Allegion_Hadoop_TransVideoSplitTool
 * Method:    SetTransVideoSplitWriteCallBack
 * Signature: (JLjava/lang/Object;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_TransVideoSplitTool_SetTransVideoSplitWriteCallBack
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     Allegion_Hadoop_TransVideoSplitTool
 * Method:    StartTrans
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_TransVideoSplitTool_StartTrans
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Allegion_Hadoop_TransVideoSplitTool
 * Method:    CloseTrans
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_TransVideoSplitTool_CloseTrans
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
