/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Allegion_Hadoop_SplitVideoFileTool */

#ifndef _Included_Allegion_Hadoop_SplitVideoFileTool
#define _Included_Allegion_Hadoop_SplitVideoFileTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Allegion_Hadoop_SplitVideoFileTool
 * Method:    InitFFmpeg
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_SplitVideoFileTool_InitFFmpeg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Allegion_Hadoop_SplitVideoFileTool
 * Method:    SetSplitReadCallBack
 * Signature: (JLjava/lang/Object;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_SplitVideoFileTool_SetSplitReadCallBack
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     Allegion_Hadoop_SplitVideoFileTool
 * Method:    SetSplitWriteCallBack
 * Signature: (JLjava/lang/Object;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_SplitVideoFileTool_SetSplitWriteCallBack
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     Allegion_Hadoop_SplitVideoFileTool
 * Method:    SetSplitNewSplitCallBack
 * Signature: (JLjava/lang/Object;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_SplitVideoFileTool_SetSplitNewSplitCallBack
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     Allegion_Hadoop_SplitVideoFileTool
 * Method:    StartSplit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_SplitVideoFileTool_StartSplit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Allegion_Hadoop_SplitVideoFileTool
 * Method:    CloseSplit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_SplitVideoFileTool_CloseSplit
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
