/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Allegion_Hadoop_MergeVideoSplitTool */

#ifndef _Included_Allegion_Hadoop_MergeVideoSplitTool
#define _Included_Allegion_Hadoop_MergeVideoSplitTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Allegion_Hadoop_MergeVideoSplitTool
 * Method:    InitFFmpeg
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_MergeVideoSplitTool_InitFFmpeg
  (JNIEnv *, jobject);

/*
 * Class:     Allegion_Hadoop_MergeVideoSplitTool
 * Method:    SetMergeReadCallBack
 * Signature: (JLjava/lang/Object;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_MergeVideoSplitTool_SetMergeReadCallBack
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     Allegion_Hadoop_MergeVideoSplitTool
 * Method:    SetMergeWriteCallBack
 * Signature: (JLjava/lang/Object;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_MergeVideoSplitTool_SetMergeWriteCallBack
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     Allegion_Hadoop_MergeVideoSplitTool
 * Method:    HaveNewSplit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_MergeVideoSplitTool_HaveNewSplit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Allegion_Hadoop_MergeVideoSplitTool
 * Method:    StartMerge
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_MergeVideoSplitTool_StartMerge
  (JNIEnv *, jobject, jlong);

/*
 * Class:     Allegion_Hadoop_MergeVideoSplitTool
 * Method:    StopMerge
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Allegion_Hadoop_MergeVideoSplitTool_StopMerge
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
